modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="bingo"
version="${file.jarVersion}"
displayName="Modded Bingo"
credits=""
authors=""
description='''
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bingo]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingo]]
    modId="bookshelf"
    mandatory=true
    versionRange="[5.6.40,)"
    ordering="AFTER"
    side="BOTH"